sudo: required
services:
   - docker
   
before_install:
   - docker build -t anushakv71/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true anushakv71/docker-react npm run test -- --coverage
